#pragma once
#define SQURE_ROOT_OF_TWO 1.414213562373095d

#define MOVINGBALL_START_POSITION_X 400
#define MOVINGBALL_START_POSITION_Y 200
#define MOVINGBALL_START_RADIUS 25

#define MOVINGBALL_REACT_RADIUS 150
#define MOVINGBALL_MAX_SPEED 200  //max speed of the ball_ (pixels/sec)

#define MOVINGBALL_MAX_SPEED_X 200  //TEMPORARY!!!
#define MOVINGBALL_MAX_SPEED_Y 200	//TEMPORARY!!!

#define CMAINDIALOG_FRAME_RATE 30
#define MOVINGBALL_MAX_ACCELERATION 20  //max acceleration (pixels/sec)